#!/usr/bin/env python
import os
import sys
import re
from pptx import Presentation
from pptx.util import Cm
import fnmatch

def show_usage():
  print "USAGE: ./extract-images pdf-file"

if len(sys.argv) < 2:
  show_usage()
  exit()

filename = sys.argv[1]

print filename

prs = Presentation(filename)

def save_image(filename, data):
    f = open(filename, 'wb')
    f.write(data)
    f.close()

_slide = 1
for slide in prs.slides:
    for shape in slide.shapes:
        num = '%03d' % _slide
        filename = "slide_%s.png" % num
        save_image(filename, shape.image.blob)
    _slide = _slide + 1
